---
- name: Create kubernetes folder
  file: 
   name: /var/lib/kubelet
   state: directory

- name: Create kubelet service
  template:
    src: "kubelet.service.j2"
    dest: "/etc/systemd/system/kubelet.service"

- name: Enale service kubelet at boot
  service:
    name: kubelet
    enabled: yes

- name: Enale service kubelet at boot
  service:
    name: kubelet
    state: started
